### ISSUE TITLE
App not working and missing

### ISSUE THREAD

**Issue by Reacien** [Wolfteam/Shiori#106]
I installed the app recently from the google play store but the features that required an internet connection aren't working for me. I tried to install the beta version, because I thought maybe that'll fix it, but the app isn't available on the google play store anymore.

I was thinking you could upload the apk to new GitHub releases so it doesn't have to be on the google play store.

I'm using a OnePlus 5T (A5010 version) running Android 10 and the latest Oxygen OS available for my device. I am also also connected to the internet at all times.

**Comment by yrret1** [comment]
Same also here, the app is not available now in google play

**Comment by JhersonCG** [comment]
It seems that the application was removed from the Play Store.
Where can I continue to update the application?

**Comment by T0matoS0up** [comment]
The same thing happened to me, and this is the best app I've ever found I want to keep updating it T﹏T)

**Comment by Wolfteam** [comment]
The app should be back on the store in a few days but with a different name and icon (cause google suspended it)

**Comment by Wolfteam** [comment]
> I installed the app recently from the google play store but the features that required an internet connection aren't working for me. I tried to install the beta version, because I thought maybe that'll fix it, but the app isn't available on the google play store anymore.
> 
> I was thinking you could upload the apk to new GitHub releases so it doesn't have to be on the google play store.
> 
> I'm using a OnePlus 5T (A5010 version) running Android 10 and the latest Oxygen OS available for my device. I am also also connected to the internet at all times.

Regarding the internet issue, what version of the app are you using ? Have you tried using a different connection (wifi / mobile) ?

**Comment by JhersonCG** [comment]
> La aplicación debería volver a estar en la tienda en unos días, pero con un nombre e ícono diferentes (porque Google la suspendió).

If you can say the new name we will all appreciate it.

**Comment by elenadokie** [comment]
> The app should be back on the store in a few days but with a different name and icon (cause google suspended it)

in the meantime is there any way to update it?

**Comment by Wolfteam** [comment]
Here's the [Link](https://play.google.com/store/apps/details?id=com.miraisoft.shiori)

**Comment by JhersonCG** [comment]
> Aquí está el [enlace](https://play.google.com/store/apps/details?id=com.miraisoft.shiori) de la nueva aplicación

I love You.  <3

**Comment by elenadokie** [comment]
> Here's the [Link](https://play.google.com/store/apps/details?id=com.miraisoft.shiori) of the new app

thank you!! <3
