### ISSUE TITLE
IOS build and release for iphones

### ISSUE THREAD

**Issue by ashkryab-fl** [Wolfteam/Shiori#117]
Hi. I am also a flutter developer, I have a mac. I can build ios build and set up bitrise for. You only need an Apple developer account.

_Originally posted by @ashkryab-fl in https://github.com/Wolfteam/Shiori/issues/113#issuecomment-922041472_

**Comment by Wolfteam** [comment]
Hiho, I prefer to have my own tooling instead of relying on third party services
