### ISSUE TITLE
Question for weapons 

### ISSUE THREAD

**Issue by Catiacchi** [Wolfteam/Shiori#128]
Hello! Thank you for all you do in this app! It's Perfect !!:))
I was wondering if... is it possible to add the new weapons like you do for itto/gorou/Shenhe por exemple? I wish to plan for the new itto's weapon but for now it's impossible :) if adding before is impossible I can understand ;)
Thanks again and have a good day!

**Comment by Wolfteam** [comment]
Hiho, I don't add upcoming weapons / artifacts because they ussually get announced a few days before the game update, so If I add them to the app I'll be leaking not announced content...

This doesn't happen with characters, cause they are ussually announced before each beta
