### ISSUE TITLE
[Localization] French/Français

### ISSUE THREAD

**Issue by MessuKilkain** [Wolfteam/Shiori#13]
Hello,
I'm a French player of Genshin impact and your app is a wonder.
I would like to know if any French localization would be possible. I can do most of the translation/check necessary if I have the localization files.
Thank you for your work and time.
Best Regards.

**Comment by Wolfteam** [comment]
Hiho, there are some french translations made by contributors, but there are a lot still missing. Send me an email to miraisoft20@gmail.com and I will send you the details

**Comment by therealcorwin** [comment]
Hi @Wolfteam ,

If you need help for French translation, i'm here :)

**Comment by Wolfteam** [comment]
> Hi @Wolfteam ,
> 
> If you need help for French translation, i'm here :)

Sure, translations are welcome, if you want more details contact me on discord wolfteam20#4750 or join the server [Discord Server](https://discord.gg/A8SgudQMwP)

**Comment by Yuki186** [comment]
hello, if you still have translation needs, I'm here.

**Comment by therealcorwin** [comment]
Hi @Yuki186, the major part of translation is finished. But due to a bug in an vcsode addon i have many corrections to do. I hope finished this week end :)

**Comment by Wolfteam** [comment]
In the latest update, french translations were added, so I'm gonna close this one
