### ISSUE TITLE
Adding energy values to ultimate/Q skills

### ISSUE THREAD

**Issue by CheshirePie** [Wolfteam/Shiori#131]
It would be super helpful if we could include the amount of energy required for every character's ult! (i.e. Chongyun 40, beidou 80)

Thanks so much to the app mod for making this super helpful database :>

**Comment by Wolfteam** [comment]
You can already see that in the character detail 
![image](https://user-images.githubusercontent.com/1976115/148113963-e9df2279-b054-41be-b43e-ea8c2f13d39c.png)
