### ISSUE TITLE
Translation mistake (Russian) | Ошибка перевода

### ISSUE THREAD

**Issue by andrei1505k** [Wolfteam/Shiori#152]
Ежедневный ~~з~~сбор
![IMG_20220528_153307.jpg](https://user-images.githubusercontent.com/60043710/170825686-e69b602f-3639-4fe5-93cf-fe61ef949ed5.jpg)

**Comment by Wolfteam** [comment]
This was fixed in 01f82926d2f0e553a7087c8979b9f617077b0b70
