### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by Myania1** [Wolfteam/Shiori#156]
Ayato signature sword "Haran Geppaku Futsu" has currently no French translation.
French translation for the sword is "Lune ondulante de Futsu" 
![Screenshot_20220610_010041](https://user-images.githubusercontent.com/107224409/172959176-2f94495a-a060-4549-a6cb-96c732b712a7.jpg)
![IMG_20220610_005727](https://user-images.githubusercontent.com/107224409/172959184-c8046c28-7c87-4b87-bf77-319709a92e85.jpg)

**Comment by Wolfteam** [comment]
Fixed in 5d3286285d16f3a2947a3ab077b97989d50342eb
