### ISSUE TITLE
Yelan

### ISSUE THREAD

**Issue by slyghykoty** [Wolfteam/Shiori#158]
mistake. she's a girl
![Скриншот 13-06-2022 125657](https://user-images.githubusercontent.com/107389358/173294468-65c0107b-6ef0-4c3e-acf6-3178416f8c8e.jpg)
![Скриншот 13-06-2022 125732](https://user-images.githubusercontent.com/107389358/173294492-d10cfdab-ccda-4838-b151-f1155614c192.jpg)

**Comment by Araratik1** [comment]
Ахаха лол

**Comment by Wolfteam** [comment]
This was fixed few weeks ago, just update the app
