### ISSUE TITLE
Ukrainian localisation 

### ISSUE THREAD

**Issue by Valeriy-Svetlichniy** [Wolfteam/Shiori#185]
Hello, I have been using your application for a long time and I would like to help make a Ukrainian localization for it, many of my friends use it, but not all of them speak English at a proper level, so I would like to help you so that it is more convenient for them to use your application.

**Comment by Wolfteam** [comment]
Hiho, sure just follow the instructions in the [README](https://github.com/Wolfteam/Shiori#translations) file

Basically just create a copy of this [file](https://github.com/Wolfteam/Shiori/blob/develop/lib/l10n/intl_en.arb) and translate the values

**Comment by Wolfteam** [comment]
> Done, I have already translated this file. Where to send it.

You could:
• Upload it here
• Send me the file via email (miraisoft20@gmail.con)
• Send me the file via discord (discord server is in the readme file and in the app)
