### ISSUE TITLE
Storage permission not working on Android 13+

### ISSUE THREAD

**Issue by RexPacificusVII** [Wolfteam/Shiori#189]
The permission to save custom builds to an image is not available anymore

**Comment by Wolfteam** [comment]
Hiho, what do you mean? The permission is only asked once 
Once you allow the app to store the img on your gallery it won't show up the permission dialog anymore

**Comment by RexPacificusVII** [comment]
Tried to check the app settings. The permission is not there. Tried to reinstall the app. Same issue. The only permissions available are Network, Notifications, and Sensors, which are all enabled on my end.

**Comment by RexPacificusVII** [comment]
Tried to check the app settings. The permission is not there. Tried to reinstall the app. Same issue. The only permissions available are Network, Notifications, and Sensors, which are all enabled on my end. No other permissions available.

Just in case it's needed, I'm using a Google Pixel 6 Pro with Graphene OS, Android 13.

**Comment by Wolfteam** [comment]
ok, it seems that this only happens on android 13... will take a look later this week

**Comment by Wolfteam** [comment]
Fixed in 7acabbb70b52264afd824db3187f52833609599b
