### ISSUE TITLE
[Suggestion] Calculator and inventory improvement

### ISSUE THREAD

**Issue by KMinorito** [Wolfteam/Shiori#191]
Very good,

The app is fantastic and is a great help, although perhaps there is an improvement that would speed up the management of game resources a lot.

Within the calculator it indicates the amount of remaining materials and when selecting one it sends you to its description.

Wouldn't it be nice to add an option to be able to update the quantity of that material? This would be faster than going to inventory and having to search for it individually.

Many thanks for everything.

**Comment by Wolfteam** [comment]
You can already do this by long pressing on the material shown in the summary

**Comment by KMinorito** [comment]
Oooh sorry, I didn't know about the option and I've been using the app for a while.  Maybe some way to make it more visible, but then I have nothing more to contribute.  I mark the thread as resolved.

Thanks!
