### ISSUE TITLE
Ukraine translate 

### ISSUE THREAD

**Issue by Scarlett911** [Wolfteam/Shiori#192]
Hello, I want to help with the translation of the application into Ukrainian, it is in the application but it is not complete, so I want to help with this, is it possible? What should I do for this?

**Comment by Scarlett911** [comment]
For example, there is no translation of artifacts, characters, weapons, this is what I want to help with

**Comment by Wolfteam** [comment]
Hi, sorry but at the moment i’m only accepting translation for the general file and not #for the specific ones (characters, artifacts, etc) due to the amount of work to properly translate those
