### ISSUE TITLE
Full Ukrainian translate 

### ISSUE THREAD

**Issue by tfrina** [Wolfteam/Shiori#200]
Greetings! I want to help to complete the Ukrainian translation in Shiori. I have a full translation of playable characters and their characteristics, artifacts, weapons, bosses, enemies and ascension materials needed. I'll be grateful to become a small part of Shiori. Thank you for your attention!

**Comment by tfrina** [comment]
I forgot to mention abt constellations and talents of the characters.

**Comment by Wolfteam** [comment]
Srry at the time i'm not accepting unofficial translations for in game stuff
