### ISSUE TITLE
Mistake in Russian translation 

### ISSUE THREAD

**Issue by Makson363** [Wolfteam/Shiori#201]
Hello, I noticed a grammatical error in the Russian translation, I did not find any way to contact Russian translators, so I write to you, on the main screen the title "Today's Ascension Materials" is correctly written as "Ежедневный сбор" but in the application it is translated as "Ежедневный збор" which is a big  mistake and it hurts so much to watch
Version 1.6.9+115

**Comment by Wolfteam** [comment]
Fixed in f51707c
