### ISSUE TITLE
[Suggestion] Switch from Wish Simulator to Realistic Wish Simulator

### ISSUE THREAD

**Issue by CroissantDuNord** [Wolfteam/Shiori#206]
The current wish simulator (https://github.com/uzair-ashraf/genshin-impact-wish-simulator) is outdated the last update was from 2 years ago, compared to other It's not very good

Currently, the best open source wish simulator is "Realistic Genshin Impact Wish Simulator" (https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator), the banners are updated, the animations are way better, and it has a mobile layout which is very useful

*(I hope there is no issue with my English, it's not my principal language)*

**Comment by Wolfteam** [comment]
Yep, I'm aware of that :C 
The good news is that i'm currently working on a native version
I'll keep this issue open until its ready
