### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by TSARukyanGT** [Wolfteam/Shiori#215]
In description of Thundering Pulse there is mistake in russian translation. Elemental Burst should be replaced by Elemental Skill and also attack can be not elemental (I marked spots) . Here is right part (numbers are right, so it does not require change), then wrong part of description and what it should be replaced with (and also english version that doesn't contain any mistakes - as a screenshot).

Right part:

> Увеличивает силу атаки на 20% и дарует мощь Громовой эмблемы. На уровнях эмблемы 1, 2 или 3 урон обычной атаки увеличивается на 12%, 24% или 40% соответственно.

Wrong part:

> Персонаж получает 1 уровень Громовой эмблемы в каждом из следующих случаев: при нанесении ***элементального*** урона обычной атакой, эмблема действует 5 сек.; при применении ***взрыва стихии***, эмблема действует 10 сек.; когда элементальная энергия персонажа ниже 100%, полученная таким образом эмблема действует до тех пор, пока персонаж не восстановит всю свою элементальную энергию. Продолжительность действия каждого уровня эмблемы рассчитывается индивидуально.

Replacement:

> Персонаж получает 1 уровень Громовой эмблемы в каждом из следующих случаев: при нанесении урона обычной атакой (эмблема действует 5 сек.); при применении ***элементального навыка*** (эмблема действует 10 сек.); когда элементальная энергия персонажа ниже 100% (эмблема исчезнет, когда элементальная энергия полностью восстановится). Продолжительность действия каждого уровня эмблемы рассчитывается индивидуально.

Also, what should i do if i will find any other mistakes? Is creating issue here a good idea?
 
![photo_2023-12-30_10-42-17](https://github.com/Wolfteam/Shiori/assets/29797897/7de2ec72-a811-46af-9767-a35e99ef7b38)

**Comment by Wolfteam** [comment]
Hi, thanks for the report. It will be fixed in the next resource update

If you find any other mistake, yes you can create a new issue so I can take a look
