### ISSUE TITLE
Ascension Materials for characters isn't showing

### ISSUE THREAD

**Issue by siriuslyelmo** [Wolfteam/Shiori#233]
i love Shiori and always using the app for calculating materials that i will need for character ascension.

today i wanted to see if Shiori already have Mavuika in the calculator, but when i added her, she didn't show up in the list. moreover the session for character doesn't show any character we want to ascend.

please help?
thank you.

**Comment by Wolfteam** [comment]
Hi, yes there was a bug with **Ororon's** skill. 
It got fixed in resource v76 but if you had it in one of your calc. sessions it will break once you update...
For now you need to manually delete the affected session and recreate it

Sorry for the inconvenience

**Comment by siriuslyelmo** [comment]
Hi!
I think you have the wrong person to reply.
My issue with Shiori was I couldn't add character/weapon to the calculator.
I wanted to add Mavuika to prepare my prefarm for her, but her details
weren't showing.
I ended up uninstalling and re-installing Shiori, and it worked OK now.

Thank you for reaching out though, and thank you for your hard work on the
Shiori App, it really helps me to prepare for upcoming characters and
weapons!

Have a nice day!

Cheers,
Elmo
