### ISSUE TITLE
Chasca's talent

### ISSUE THREAD

**Issue by Seza1n** [Wolfteam/Shiori#234]
The priority for ascension Chaska's skills is not correct, a normal  attack does not give her anything, The priority should be like this: elemental skill > elemental Burst> normal attack
![IMG_20241124_135913](https://github.com/user-attachments/assets/a326b971-9d27-43ed-bc9b-0f9640f97eb3)

**Comment by Wolfteam** [comment]
Hi, thanks for the report, it was fixed in resource v77
