### ISSUE TITLE
Inventory & Calculator lists not working properly 

### ISSUE THREAD

**Issue by Momochiiee** [Wolfteam/Shiori#235]
The latest update seems to have broken both functions, the Inventory and Calculator lists and it's connected function

The app seems to need to be closed and restarted for any changes in the Inventory to be reflected, and the Calculator material usage seems to not refresh at all

Also I have one of my Calculator lists telling me I have 6 characters in it but once I go into it it's display is completely empty

Hope this helps to identify where the problems may be!
Thank you for your hard work making such an amazing tool!

**Comment by Wolfteam** [comment]
Hi, yes there was a bug with **Ororon's** skill. 
It got fixed in resource v76 but if you had it in one of your calc. sessions it will break once you update...
For now you need to manually delete the affected session and recreate it

Sorry for the inconvenience
