### ISSUE TITLE
iOs support

### ISSUE THREAD

**Issue by HG5667** [Wolfteam/Shiori#38]
Hi,

I was wondering if you could make this app available on Android and ios devices both. Thanks!

**Comment by Wolfteam** [comment]
I don't have a mac to compile the app for ios :C

**Comment by HG5667** [comment]
Oh. Sad.

**Comment by ashkryab-fl** [comment]
I have mac. I can help u. I can prepare codemagic or bitrise for automatisation. Its free, u need only apple dev account
