### ISSUE TITLE
Translation German

### ISSUE THREAD

**Issue by KimElif** [Wolfteam/Shiori#47]
Hello I don't know if someone already is doing it but I would like to help translate this app into German, i really like this app and many of my friends are using it.

**Comment by Wolfteam** [comment]
There is currently only one person working on the German translations (the main file is 5000 + lines long), if you would like to help, you can join the discord server https://discord.gg/A8SgudQMwP

**Comment by Wolfteam** [comment]
In the latest update, the german translations were added, so I'm gonna close this one
