### ISSUE TITLE
Add Inventory edit shortcut to calculator 

### ISSUE THREAD

**Issue by TomR24** [Wolfteam/Shiori#83]
I'd be nice to have a quick way to change the amount of a certain item you have in your inventory while remaining in the calculator tab, for example by long pressing on an item to show the pop up window that shows up in the inventory tab when editing the item count. This would eliminate the need to switch back and forth between the inventory and calculator tab.

**Comment by Quintasan** [comment]
This got implemented in https://github.com/Wolfteam/Shiori/pull/112

**Comment by Quintasan** [comment]
@Wolfteam I think we can close this now.
